[2025-07-16T21:28:41.250+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:27:27.492219+00:00 [queued]>
[2025-07-16T21:28:41.255+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:27:27.492219+00:00 [queued]>
[2025-07-16T21:28:41.256+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-16T21:28:41.264+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fail_task> on 2025-07-16 21:27:27.492219+00:00
[2025-07-16T21:28:41.266+0000] {standard_task_runner.py:57} INFO - Started process 7433 to run task
[2025-07-16T21:28:41.267+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'fail_task', 'scheduled__2025-07-16T21:27:27.492219+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmpfynvptmr']
[2025-07-16T21:28:41.269+0000] {standard_task_runner.py:85} INFO - Job 613: Subtask fail_task
[2025-07-16T21:28:41.289+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:27:27.492219+00:00 [running]> on host 66ed94c0a57f
[2025-07-16T21:28:41.328+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='fail_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T21:27:27.492219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T21:27:27.492219+00:00'
[2025-07-16T21:28:41.328+0000] {logging_mixin.py:150} INFO - Executing fail task - Failure path
[2025-07-16T21:28:41.329+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-16 21:28:41.329003
[2025-07-16T21:28:41.329+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_build_monolith.py", line 55, in fail_task
    raise ValueError("This task is designed to fail on even minutes")
ValueError: This task is designed to fail on even minutes
[2025-07-16T21:28:41.332+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=fail_task, execution_date=20250716T212727, start_date=20250716T212841, end_date=20250716T212841
[2025-07-16T21:28:41.336+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 613 for task fail_task (This task is designed to fail on even minutes; 7433)
[2025-07-16T21:28:41.366+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-16T21:28:41.376+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
