[2025-07-17T07:32:53.326+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-17T07:31:39.368956+00:00 [queued]>
[2025-07-17T07:32:53.331+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-17T07:31:39.368956+00:00 [queued]>
[2025-07-17T07:32:53.331+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-17T07:32:53.337+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fail_task> on 2025-07-17 07:31:39.368956+00:00
[2025-07-17T07:32:53.339+0000] {standard_task_runner.py:57} INFO - Started process 1971 to run task
[2025-07-17T07:32:53.340+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'fail_task', 'scheduled__2025-07-17T07:31:39.368956+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmp11f6t2o4']
[2025-07-17T07:32:53.341+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask fail_task
[2025-07-17T07:32:53.359+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-17T07:31:39.368956+00:00 [running]> on host 515ade4cdc0f
[2025-07-17T07:32:53.396+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='fail_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T07:31:39.368956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-17T07:31:39.368956+00:00'
[2025-07-17T07:32:53.396+0000] {logging_mixin.py:150} INFO - Executing fail task - Failure path
[2025-07-17T07:32:53.396+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-17 07:32:53.396767
[2025-07-17T07:32:53.396+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_build_monolith.py", line 55, in fail_task
    raise ValueError("This task is designed to fail on even minutes")
ValueError: This task is designed to fail on even minutes
[2025-07-17T07:32:53.399+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=fail_task, execution_date=20250717T073139, start_date=20250717T073253, end_date=20250717T073253
[2025-07-17T07:32:53.404+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 19 for task fail_task (This task is designed to fail on even minutes; 1971)
[2025-07-17T07:32:53.438+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-17T07:32:53.447+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
