[2025-07-16T10:20:06.913+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T10:18:53.814825+00:00 [queued]>
[2025-07-16T10:20:06.918+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T10:18:53.814825+00:00 [queued]>
[2025-07-16T10:20:06.918+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-16T10:20:06.924+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fail_task> on 2025-07-16 10:18:53.814825+00:00
[2025-07-16T10:20:06.926+0000] {standard_task_runner.py:57} INFO - Started process 10361 to run task
[2025-07-16T10:20:06.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'fail_task', 'scheduled__2025-07-16T10:18:53.814825+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmprvgmi7xu']
[2025-07-16T10:20:06.929+0000] {standard_task_runner.py:85} INFO - Job 333: Subtask fail_task
[2025-07-16T10:20:06.946+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T10:18:53.814825+00:00 [running]> on host 0f12c04aebf5
[2025-07-16T10:20:06.984+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='fail_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T10:18:53.814825+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T10:18:53.814825+00:00'
[2025-07-16T10:20:06.984+0000] {logging_mixin.py:150} INFO - Executing fail task - Failure path
[2025-07-16T10:20:06.985+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-16 10:20:06.985032
[2025-07-16T10:20:06.985+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_build_monolith.py", line 55, in fail_task
    raise ValueError("This task is designed to fail on even minutes")
ValueError: This task is designed to fail on even minutes
[2025-07-16T10:20:06.988+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=fail_task, execution_date=20250716T101853, start_date=20250716T102006, end_date=20250716T102006
[2025-07-16T10:20:06.992+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 333 for task fail_task (This task is designed to fail on even minutes; 10361)
[2025-07-16T10:20:07.026+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-16T10:20:07.035+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
