[2025-07-15T19:46:36.052+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:46:35.017127+00:00 [queued]>
[2025-07-15T19:46:36.055+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:46:35.017127+00:00 [queued]>
[2025-07-15T19:46:36.055+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:46:36.062+0000] {taskinstance.py:1327} INFO - Executing <Task(RecentExternalTaskSensor): wait_for_etl_failure> on 2025-07-15 19:46:35.017127+00:00
[2025-07-15T19:46:36.064+0000] {standard_task_runner.py:57} INFO - Started process 4350 to run task
[2025-07-15T19:46:36.065+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_failure_sensor', 'wait_for_etl_failure', 'manual__2025-07-15T19:46:35.017127+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/failure_sensor_dag.py', '--cfg-path', '/tmp/tmplzz7ls_t']
[2025-07-15T19:46:36.066+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask wait_for_etl_failure
[2025-07-15T19:46:36.084+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:46:35.017127+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:46:36.120+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_failure_sensor' AIRFLOW_CTX_TASK_ID='wait_for_etl_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:46:35.017127+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:46:35.017127+00:00'
[2025-07-15T19:46:36.124+0000] {recent_external_task_sensor.py:41} INFO - Poking for dbt_build_monolith.fail_task between 2025-07-15T17:46:36.124319+00:00 and 2025-07-15T19:46:36.124319+00:00, looking for states: ['failed']
[2025-07-15T19:46:36.130+0000] {recent_external_task_sensor.py:70} INFO - Found task instance <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-15T19:39:43.374004+00:00 [failed]> with state failed (end_date: 2025-07-15 19:42:57.751339+00:00)
[2025-07-15T19:46:36.130+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2025-07-15T19:46:36.133+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_failure_sensor, task_id=wait_for_etl_failure, execution_date=20250715T194635, start_date=20250715T194636, end_date=20250715T194636
[2025-07-15T19:46:36.162+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-15T19:46:36.204+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
