[2025-07-16T21:24:24.095+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:23:11.059887+00:00 [queued]>
[2025-07-16T21:24:24.099+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:23:11.059887+00:00 [queued]>
[2025-07-16T21:24:24.100+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-16T21:24:24.106+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fail_task> on 2025-07-16 21:23:11.059887+00:00
[2025-07-16T21:24:24.108+0000] {standard_task_runner.py:57} INFO - Started process 6888 to run task
[2025-07-16T21:24:24.109+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'fail_task', 'scheduled__2025-07-16T21:23:11.059887+00:00', '--job-id', '585', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmp9oddx02x']
[2025-07-16T21:24:24.110+0000] {standard_task_runner.py:85} INFO - Job 585: Subtask fail_task
[2025-07-16T21:24:24.128+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-16T21:23:11.059887+00:00 [running]> on host 66ed94c0a57f
[2025-07-16T21:24:24.163+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='fail_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T21:23:11.059887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T21:23:11.059887+00:00'
[2025-07-16T21:24:24.164+0000] {logging_mixin.py:150} INFO - Executing fail task - Failure path
[2025-07-16T21:24:24.164+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-16 21:24:24.164344
[2025-07-16T21:24:24.164+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_build_monolith.py", line 55, in fail_task
    raise ValueError("This task is designed to fail on even minutes")
ValueError: This task is designed to fail on even minutes
[2025-07-16T21:24:24.167+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=fail_task, execution_date=20250716T212311, start_date=20250716T212424, end_date=20250716T212424
[2025-07-16T21:24:24.171+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 585 for task fail_task (This task is designed to fail on even minutes; 6888)
[2025-07-16T21:24:24.207+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-16T21:24:24.216+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
