[2025-07-16T09:03:13.155+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.process_task scheduled__2025-07-16T09:00:10.789371+00:00 [queued]>
[2025-07-16T09:03:13.159+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.process_task scheduled__2025-07-16T09:00:10.789371+00:00 [queued]>
[2025-07-16T09:03:13.159+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-16T09:03:13.166+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_task> on 2025-07-16 09:00:10.789371+00:00
[2025-07-16T09:03:13.168+0000] {standard_task_runner.py:57} INFO - Started process 1412 to run task
[2025-07-16T09:03:13.170+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'process_task', 'scheduled__2025-07-16T09:00:10.789371+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmp5_0_7k8m']
[2025-07-16T09:03:13.171+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask process_task
[2025-07-16T09:03:13.191+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.process_task scheduled__2025-07-16T09:00:10.789371+00:00 [running]> on host 0f12c04aebf5
[2025-07-16T09:03:13.229+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='process_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T09:00:10.789371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T09:00:10.789371+00:00'
[2025-07-16T09:03:13.229+0000] {logging_mixin.py:150} INFO - Processing for 10 seconds...
[2025-07-16T09:03:23.232+0000] {logging_mixin.py:150} INFO - completed
[2025-07-16T09:03:23.232+0000] {python.py:183} INFO - Done. Returned value was: Processing task completed
[2025-07-16T09:03:23.236+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2361, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 214, in set
    raise ValueError(f"DAG run not found on DAG {dag_id!r} with ID {run_id!r}")
ValueError: DAG run not found on DAG 'dbt_build_monolith' with ID 'scheduled__2025-07-16T09:00:10.789371+00:00'
[2025-07-16T09:03:23.243+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=process_task, execution_date=20250716T090010, start_date=20250716T090313, end_date=20250716T090323
[2025-07-16T09:03:23.251+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 66 for task process_task ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(dbt_build_monolith, process_task, scheduled__2025-07-16T09:00:10.789371+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'process_task', 'dag_id': 'dbt_build_monolith', 'run_id': 'scheduled__2025-07-16T09:00:10.789371+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 7, 16, 9, 3, 13, 155862, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 7, 16, 9, 3, 23, 243185, tzinfo=Timezone('UTC')), 'duration': 10}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1412)
[2025-07-16T09:03:23.265+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
