[2025-07-15T19:51:37.751+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:51:34.960042+00:00 [queued]>
[2025-07-15T19:51:37.755+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:51:34.960042+00:00 [queued]>
[2025-07-15T19:51:37.755+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:51:37.762+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): delay_task> on 2025-07-15 19:51:34.960042+00:00
[2025-07-15T19:51:37.764+0000] {standard_task_runner.py:57} INFO - Started process 4963 to run task
[2025-07-15T19:51:37.765+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_success_sensor', 'delay_task', 'manual__2025-07-15T19:51:34.960042+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/success_sensor_dag.py', '--cfg-path', '/tmp/tmpoz5npb7x']
[2025-07-15T19:51:37.766+0000] {standard_task_runner.py:85} INFO - Job 113: Subtask delay_task
[2025-07-15T19:51:37.786+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:51:34.960042+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:51:37.818+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_success_sensor' AIRFLOW_CTX_TASK_ID='delay_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:51:34.960042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:51:34.960042+00:00'
[2025-07-15T19:51:37.818+0000] {logging_mixin.py:150} INFO - Delaying for 2 hours...
[2025-07-15T19:57:03.557+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-15T19:57:03.581+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 4963. PIDs of all processes in the group: [4963]
[2025-07-15T19:57:03.582+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 4963
[2025-07-15T19:57:03.584+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-15T19:57:03.604+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/success_sensor_dag.py", line 54, in delay_task
    time.sleep(LOOK_BACK_HOURS * 3600)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-07-15T19:57:03.608+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_success_sensor, task_id=delay_task, execution_date=20250715T195134, start_date=20250715T195137, end_date=20250715T195703
[2025-07-15T19:57:03.615+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 113 for task delay_task (Task received SIGTERM signal; 4963)
[2025-07-15T19:57:03.639+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4963, status='terminated', exitcode=1, started='19:51:37') (4963) terminated with exit code 1
[2025-07-15T19:57:03.640+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2025-07-15T19:57:03.654+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
