[2025-07-15T19:40:02.830+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-15T19:36:43.374004+00:00 [queued]>
[2025-07-15T19:40:02.834+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-15T19:36:43.374004+00:00 [queued]>
[2025-07-15T19:40:02.835+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-15T19:40:02.841+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fail_task> on 2025-07-15 19:36:43.374004+00:00
[2025-07-15T19:40:02.843+0000] {standard_task_runner.py:57} INFO - Started process 3643 to run task
[2025-07-15T19:40:02.844+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_build_monolith', 'fail_task', 'scheduled__2025-07-15T19:36:43.374004+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dbt_build_monolith.py', '--cfg-path', '/tmp/tmpxixmo1zm']
[2025-07-15T19:40:02.845+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask fail_task
[2025-07-15T19:40:02.863+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-15T19:36:43.374004+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:40:02.895+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_build_monolith' AIRFLOW_CTX_TASK_ID='fail_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:36:43.374004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T19:36:43.374004+00:00'
[2025-07-15T19:40:02.895+0000] {logging_mixin.py:150} INFO - Executing fail task - Failure path
[2025-07-15T19:40:02.895+0000] {logging_mixin.py:150} INFO - Current time: 2025-07-15 19:40:02.895796
[2025-07-15T19:40:02.895+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_build_monolith.py", line 52, in fail_task
    raise ValueError("This task is designed to fail on even minutes")
ValueError: This task is designed to fail on even minutes
[2025-07-15T19:40:02.898+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_build_monolith, task_id=fail_task, execution_date=20250715T193643, start_date=20250715T194002, end_date=20250715T194002
[2025-07-15T19:40:02.903+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 21 for task fail_task (This task is designed to fail on even minutes; 3643)
[2025-07-15T19:40:02.945+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-15T19:40:02.954+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
