[2025-07-15T19:39:39.537+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [queued]>
[2025-07-15T19:39:39.541+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [queued]>
[2025-07-15T19:39:39.541+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:39:39.548+0000] {taskinstance.py:1327} INFO - Executing <Task(RecentExternalTaskSensor): wait_for_etl_failure> on 2025-07-15 19:39:38.351041+00:00
[2025-07-15T19:39:39.549+0000] {standard_task_runner.py:57} INFO - Started process 3605 to run task
[2025-07-15T19:39:39.551+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_failure_sensor', 'wait_for_etl_failure', 'manual__2025-07-15T19:39:38.351041+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/failure_sensor_dag.py', '--cfg-path', '/tmp/tmptt2micky']
[2025-07-15T19:39:39.552+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask wait_for_etl_failure
[2025-07-15T19:39:39.571+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:39:39.605+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_failure_sensor' AIRFLOW_CTX_TASK_ID='wait_for_etl_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:39:38.351041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:39:38.351041+00:00'
[2025-07-15T19:39:39.608+0000] {recent_external_task_sensor.py:41} INFO - Poking for dbt_build_monolith.fail_task between 2025-07-15T17:39:39.608920+00:00 and 2025-07-15T19:39:39.608920+00:00, looking for states: ['failed']
[2025-07-15T19:39:39.613+0000] {recent_external_task_sensor.py:64} INFO - No matching task instances found within the time window.
[2025-07-15T19:39:39.621+0000] {taskinstance.py:1784} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-07-15T19:39:39.647+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-15T19:39:39.660+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T19:40:09.939+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [queued]>
[2025-07-15T19:40:09.943+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [queued]>
[2025-07-15T19:40:09.943+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:40:09.949+0000] {taskinstance.py:1327} INFO - Executing <Task(RecentExternalTaskSensor): wait_for_etl_failure> on 2025-07-15 19:39:38.351041+00:00
[2025-07-15T19:40:09.951+0000] {standard_task_runner.py:57} INFO - Started process 3664 to run task
[2025-07-15T19:40:09.953+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_failure_sensor', 'wait_for_etl_failure', 'manual__2025-07-15T19:39:38.351041+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/failure_sensor_dag.py', '--cfg-path', '/tmp/tmp6w7c_7kq']
[2025-07-15T19:40:09.954+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask wait_for_etl_failure
[2025-07-15T19:40:09.973+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_failure_sensor.wait_for_etl_failure manual__2025-07-15T19:39:38.351041+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:40:10.004+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_failure_sensor' AIRFLOW_CTX_TASK_ID='wait_for_etl_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:39:38.351041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:39:38.351041+00:00'
[2025-07-15T19:40:10.008+0000] {recent_external_task_sensor.py:41} INFO - Poking for dbt_build_monolith.fail_task between 2025-07-15T17:40:10.008337+00:00 and 2025-07-15T19:40:10.008337+00:00, looking for states: ['failed']
[2025-07-15T19:40:10.014+0000] {recent_external_task_sensor.py:70} INFO - Found task instance <TaskInstance: dbt_build_monolith.fail_task scheduled__2025-07-15T19:36:43.374004+00:00 [failed]> with state failed (end_date: 2025-07-15 19:40:02.898624+00:00)
[2025-07-15T19:40:10.014+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2025-07-15T19:40:10.019+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_failure_sensor, task_id=wait_for_etl_failure, execution_date=20250715T193938, start_date=20250715T194009, end_date=20250715T194010
[2025-07-15T19:40:10.050+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-15T19:40:10.066+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
