[2025-07-15T19:55:35.764+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:55:33.317900+00:00 [queued]>
[2025-07-15T19:55:35.768+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:55:33.317900+00:00 [queued]>
[2025-07-15T19:55:35.768+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-15T19:55:35.775+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): delay_task> on 2025-07-15 19:55:33.317900+00:00
[2025-07-15T19:55:35.777+0000] {standard_task_runner.py:57} INFO - Started process 5337 to run task
[2025-07-15T19:55:35.779+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_success_sensor', 'delay_task', 'manual__2025-07-15T19:55:33.317900+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/success_sensor_dag.py', '--cfg-path', '/tmp/tmprfi98zk2']
[2025-07-15T19:55:35.780+0000] {standard_task_runner.py:85} INFO - Job 124: Subtask delay_task
[2025-07-15T19:55:35.800+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_success_sensor.delay_task manual__2025-07-15T19:55:33.317900+00:00 [running]> on host 1e79179934e4
[2025-07-15T19:55:35.832+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_success_sensor' AIRFLOW_CTX_TASK_ID='delay_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T19:55:33.317900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T19:55:33.317900+00:00'
[2025-07-15T19:55:35.832+0000] {logging_mixin.py:150} INFO - Delaying for 2 hours...
[2025-07-15T19:57:03.557+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-15T19:57:03.572+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 5337. PIDs of all processes in the group: [5337]
[2025-07-15T19:57:03.575+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 5337
[2025-07-15T19:57:03.575+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-15T19:57:03.601+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/success_sensor_dag.py", line 54, in delay_task
    time.sleep(LOOK_BACK_HOURS * 3600)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-07-15T19:57:03.607+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_success_sensor, task_id=delay_task, execution_date=20250715T195533, start_date=20250715T195535, end_date=20250715T195703
[2025-07-15T19:57:03.615+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 124 for task delay_task (Task received SIGTERM signal; 5337)
[2025-07-15T19:57:03.635+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5337, status='terminated', exitcode=1, started='19:55:35') (5337) terminated with exit code 1
[2025-07-15T19:57:03.637+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2025-07-15T19:57:03.654+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
